name: Pylint

on:
  push:
    branches: ["main"]
    paths:
      - "*.py"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --errors-only
